### ISSUE TITLE
broken logo in home page

### ISSUE THREAD

**Issue by arshadkazmi42** [unauthapp/unauthapp.github.io#18]
![Screenshot from 2019-10-25 23-42-01](https://user-images.githubusercontent.com/4654382/67594106-40b5aa00-f781-11e9-98bb-1ec53cebb2b5.png)

Broken in fedora > firefox

**Comment by Grigory57** [comment]
I'll work on that

**Comment by arshadkazmi42** [comment]
@Grigory57 Sure go ahead.

**Comment by Grigory57** [comment]
Sorry, It needs Fedora. I don't have it.
