### ISSUE TITLE
Add social media links &  email on footer

### ISSUE THREAD

**Issue by sinumohan** [unauthapp/unauthapp.github.io#20]
**Add footer buttons with following button links**
------------------------------------------
FB: https://www.facebook.com/unauthapp
Twitter: https://twitter.com/unauthapp
Email: unauth.cloud@gmail.com

**Comment by AlexanderMalmstrom** [comment]
working on it

**Comment by arshadkazmi42** [comment]
@AlexanderMalmstrom Great 👍
